[package]
name = "video-audio-voice-activity-detection"
version = "0.1.0"
edition = "2021"

[dependencies]
video-audio-decoder = { path = "../video-decoder" }
video-extract-core = { path = "../video-extract-core" }
anyhow = "1.0"
async-trait = "0.1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tracing = "0.1"
webrtc-vad = "0.4"
