[package]
name = "video-audio-extractor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
video-audio-common = { path = "../common" }
video-extract-core = { path = "../video-extract-core" }
video-audio-decoder = { path = "../video-decoder" }
async-trait = "0.1"
tracing = "0.1"
serde_yaml = "0.9"

[dev-dependencies]
tempfile = "3.8"
