[package]
name = "video-audio-keyframe"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
video-audio-common = { path = "../common" }
video-audio-decoder = { path = "../video-decoder" }
video-extract-core = { path = "../video-extract-core" }
image.workspace = true
async-trait = "0.1"
tracing = "0.1"
serde_yaml = "0.9"
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.8"
